version: "3"
services:
  server:
    build: .
    ports:
      - "8081:8081"

  server_config:
    build: .
    ports:
      - "8081:8081"
    environment:
      - OPA_POLICY_FOLDER=/policy/
      - LOG_LEVEL=debug
    volumes:
      - ./test_policies:/policy
      - ./test_policies:/policy/subdir
