apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-auth-jwt.fullname" . }}
  labels:
    {{- include "aws-auth-jwt.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aws-auth-jwt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aws-auth-jwt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aws-auth-jwt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ISSUER
              value: {{ .Values.jwt.issuer }}
          {{- with .Values.jwt.publicKeyFile }}
            - name: PUBLIC_KEY_FILE
              value: {{ . }}
          {{- end }}
          {{- with .Values.jwt.privateKeyFile }}
            - name: PRIVATE_KEY_FILE
              value: {{ . }}
          {{- end }}
          {{- with .Values.jwt.tokenExpirationHours }}
            - name: TOKEN_EXPIRATION_HOURS
              value: {{ . | quote }}
          {{- end }}
          {{- if .Values.opa.policyInline }}
            - name: OPA_POLICY_FOLDER
              value: /policy/
          {{- end }}
          {{- with .Values.logLevel }}
            - name: LOG_LEVEL
              value: {{ . }}
          {{- end }}
          {{- if .Values.env }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: policy
              mountPath: /policy
            {{- if .Values.certificateSecretName }}
            - name: certificate
              mountPath: /certs
            {{- end }}
            {{- with .Values.additionalVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: policy
          configMap:
            name: {{ include "aws-auth-jwt.fullname" . }}-policy
        {{- if .Values.certificateSecretName }}
        - name: certificate
          secret:
            secretName: {{ .Values.certificateSecretName }}
        {{- end }}
        {{- with .Values.additionalVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
