apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-auth-jwt.fullname" . }}
  labels: {{- include "aws-auth-jwt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "aws-auth-jwt.selectorLabels" . | nindent 4 }}
