name: Build and Publish Docker Image

# on release tag
on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/aws-auth-jwt:${{  github.ref_name }} .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/aws-auth-jwt:${{  github.ref_name }}
