name: Build and Publish Docker Image

# on release tag
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/aws-auth-jwt:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.Client
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/aws-auth-jwt-client:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract amd64 client binary
        run: |
          set -e
          container_id=$(docker create --platform linux/amd64 ghcr.io/${{ github.repository }}/aws-auth-jwt-client:${{ github.ref_name }})
          docker cp $container_id:/aws_auth_jwt_client ./linux-client-amd64
          docker rm $container_id

      - name: Extract arm64 client binary
        run: |
          set -e
          container_id=$(docker create --platform linux/arm64 ghcr.io/${{ github.repository }}/aws-auth-jwt-client:${{ github.ref_name }})
          docker cp $container_id:/aws_auth_jwt_client ./linux-client-arm64
          docker rm $container_id

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "linux-client-amd64,linux-client-arm64"
          generateReleaseNotes: true
          allowUpdates: true
